default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: AcqufLEu849kHE7K
  host: localhost

development:
  <<: *default
  database: transchat_development

test:
  <<: *default
  database: transchat_test

production:
  <<: *default
  database: <%= ENV['TRANSCHAT_DATABASE_NAME'] %>
  password: <%= ENV['TRANSCHAT_DATABASE_PASSWORD'] %>
